name: 'Oysho autorun test on Cypress'
run-name: Oysho Test
on: 
  push:
    branches: [main]
  schedule:
      - cron: "0 23 * * *"
    
jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.4.0"
          cache: npm

      - name: Install Dependencies
        run: npm install
      
      - name: Cypress.io
        uses: cypress-io/github-action@v5
        with: 
          build: npm run build
          browser: chrome
          start: npm run oysho:run
          wait-on: 'https://www.oysho.com'
          wait-on-timeout: 120
          record: true
        