name: 'Oysho autorun test on Cypress'
run-name: Oysho Test
on: 
  push:
    branches: [main]
  schedule:
      - cron: "0 23 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Test Artifacts
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: ./cypress/videos
    
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.4.0"
          cache: npm

      - name: Install Dependencies
        run: npm install
      
      - name: Cypress.io
        uses: cypress-io/github-action@v4
        with: 
          start: npm run oysho:run --headed
          record: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
